(ns knossos.wgl.stress-test
  (:require [clojure.test :refer :all]
            [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.pprint :refer [pprint]]
            [clojure.tools.logging :refer :all]
            [knossos.model :as model]
            [knossos.wgl :as wgl]
            [knossos.memory :as memory])
  (:import (java.io PushbackReader)))

(defn tuple?
  "Is the given value generated by an independent generator?"
  [value]
  (instance? clojure.lang.MapEntry value))

(defn histories
  "A map of object ids to histories on that object"
  []
  (with-open [r (PushbackReader. (io/reader "data/memstress3.edn"))]
    (->> (repeatedly #(edn/read {:eof nil} r))
         (take-while identity)
         (reduce (fn [m [process type f [k value]]]
                   (let [hist (get m k [])]
                     (assoc m k (conj hist {:process process
                                            :type    type
                                            :f       f
                                            :value   value}))))
                 (sorted-map)))))

(deftest stress-test
  (doseq [[k history] (histories)]
    (info k (:valid? (wgl/analysis (model/cas-register 0) history)))))
